/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tf_test_SerialPort */

#ifndef _Included_tf_test_SerialPort
#define _Included_tf_test_SerialPort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tf_test_SerialPort
 * Method:    open
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_tf_test_SerialPort_open
  (JNIEnv *, jclass, jstring);

/*
 * Class:     tf_test_SerialPort
 * Method:    close
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_tf_test_SerialPort_close
  (JNIEnv *, jclass, jint);

/*
 * Class:     tf_test_SerialPort
 * Method:    writeData
 * Signature: (ILjava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_tf_test_SerialPort_writeData
  (JNIEnv *, jclass, jint, jstring);

/*
 * Class:     tf_test_SerialPort
 * Method:    receiveData
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_tf_test_SerialPort_receiveData
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
