#ifndef __SPECIALKEYFORCIT_H__
#define __SPECIALKEYFORCIT_H__

#define GPIO_IOC_MAGIC 0x90
#define GPIO_IOCQPULLEN  _IOR(GPIO_IOC_MAGIC, 0x09, uint32_t)
#define GPIO_IOCQDIR  _IOR(GPIO_IOC_MAGIC, 0x06, uint32_t)
#define GPIO_IOCQDATAOUT  _IOR(GPIO_IOC_MAGIC, 0x13, uint32_t)
#define GPIO_IOCQDATAIN _IOR(GPIO_IOC_MAGIC, 0x12,  uint32_t)
#endif
