/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class tf_test_SpecialKey */

#ifndef _Included_tf_test_SpecialKey
#define _Included_tf_test_SpecialKey
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     tf_test_SpecialKey
 * Method:    startListenthread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tf_test_SpecialKey_startListenthread
  (JNIEnv *, jobject);

/*
 * Class:     tf_test_SpecialKey
 * Method:    stopListenthread
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_tf_test_SpecialKey_stopListenthread
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
